config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'sitemap.xml', to: "sitemap#show"
  mount PgHero::Engine, at: "pghero"

  if Rails.env.development? || Rails.env.test?
    mount Rswag::Ui::Engine => '/api-docs'
    mount Rswag::Api::Engine => '/api-docs'
  end

  ActiveAdmin.routes(self)
  root to: 'static_pages#home'
  resources :discounts, only: [:index, :show], param: :slug

  namespace :api do
    resources :products, only: [:index, :create] do
      delete :destroy, on: :collection
    end

    resources :promotions, only: [:index]
    resources :users, only: [:create] do
      put :update, on: :collection
    end
  end

  if Rails.env.production? || Rails.env.staging?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV.fetch("ADMIN_LOGIN"))) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV.fetch("ADMIN_PASSWORD")))
    end
  end

  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/discount.rb
class Discount < ApplicationRecord
  MAX_FRESH_AGE = 2.month.ago
  belongs_to :product
  delegate :currency, to: :product, allow_nil: true, prefix: false

  scope :was_tweeted, -> {
    where(was_tweeted: true)
  }

  scope :recent, -> {
     where("discounts.created_at > ?", MAX_FRESH_AGE)
  }

  def self.total_usd_value
    where(id: select("distinct on (product_id) id")).sum(:usd_value).to_f
  end

  def self.uniq_apps_count
    where(id: select("distinct on (store_id) id")).count
  end

  def update_usd_prices
    return unless currency
    return unless currency_object = Currency.find_by(name: currency)
    return unless rate = currency_object.usd_rate

    from_price_usd_val = from_price / rate
    to_price_usd_val = to_price / rate
    update!(
      from_price_usd: from_price_usd_val,
      to_price_usd: to_price_usd_val,
      usd_value: from_price_usd_val - to_price_usd_val
    )
  end

  def value
    (from_price - to_price).to_f.round(2)
  end

  def ratio
    return 100 if from_price.to_f == 0.0

    diff = from_price.to_f - to_price.to_f

    return 100 if diff == 0.0

    ((diff / from_price) * 100).round(0).to_i
  end
end

app/controllers/discounts_controller.rb
class DiscountsController < WebBaseController
  before_action :product, only: [:show]

  def index
    respond_to do |format|
      format.html
      format.json do
        redirect_to api_promotions_path
      end
    end
  end

  def show
    raise ActiveRecord::RecordNotFound unless product.fetch(:is_discounted)
    @show_title = "App Store discount #{product.fetch(:discount_ratio)}% off '#{product.fetch(:name)}'"
    @page_title = "#{@show_title} - Smart Wishlist"
    @page_description = "'#{product.fetch(:name)}' is currently discounted from #{product.fetch(:base_price_formatted)} to #{product.fetch(:current_price_formatted)} on iOS App Store."
    @page_image = product.fetch(:preview_icon)
  end

  private

  def product
    @product ||= Product::Serializer.new(Product.find_by!(slug: params.fetch(:slug))).to_json
  end
end

app/views/discounts/index.slim
.top-25
= link_to "Home", root_path, class: 'btn btn-primary no-underline bright-color discounts-home-button'
a href="#{@app_store_link}" target='_blank'
  = image_tag "app_store_button.svg", width: "120px", class: 'discounts-store-button'
a href="#{@app_store_link}" target='_blank'
  = image_tag "wishlist-icon.png", height: "35px", class: 'discounts-app-icon'

div.text-center
  h1.text-muted Currently discounted
  div id='react-table'

app/views/discounts/show.slim
script type="application/ld+json"
  | {
  | "@context": "http://schema.org",
  | "@type": "SoftwareApplication",
  | "name": "#{@product.fetch(:name)}",
  | "operatingSystem": "iOS",
  | "applicationCategory": "http://schema.org/SoftwareApplication",
  | "aggregateRating": {
  | "@type": "AggregateRating",
  | "ratingValue": "#{@product.fetch(:average_user_rating)}",
  | "ratingCount": "#{@product.fetch(:user_rating_count)}"
  | },
  | "offers": {
  | "@type": "Offer",
  | "price": "#{@product.fetch(:current_price)}",
  | "priceCurrency": "USD"
  | }
  | }

.top-25
= link_to "Home", root_path, class: 'btn btn-primary btn-lg no-underline bright-color discounts-home-button right-20'
= link_to "All discounts", discounts_path, class: 'btn btn-primary btn-lg no-underline bright-color discounts-home-button'

.content-section-a.top-25.discount-details
  .container
    .row
      .col-lg-6.col-sm-6.text-center
        div.bottom-5
          img.app-icon src="#{@product.fetch(:big_icon_url)}" alt="#{@product.fetch(:name)} icon"
        div.btn-group.top-5 role="group"
          div.btn.btn-default.btn-lg.no-click Now #{ @product.fetch(:current_price_formatted) }
          div.btn.btn-default.btn-lg.no-click from #{ @product.fetch(:base_price_formatted) }
        div.top-5
          a href="#{@product.fetch(:store_url)}" target='_blank'
            = image_tag "app_store_button.svg", width: "40%", class: 'discounts-store-button', alt: "#{@product.fetch(:name)} App Store button"
      .col-lg-6.col-sm-6
        h1.section-heading.text-muted
          | #{@show_title}
        .lead
          i #{ simple_format @product.fetch(:description)}
        .bottom-20